# Generated by Django 5.2.6 on 2026-03-30 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('note', models.TextField()),
                ('container', models.CharField(max_length=250)),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('risk_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.CharField(max_length=255)),
                ('risk_manager', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_derector', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible', models.CharField(max_length=255)),
                ('created_by_user_id', models.CharField(max_length=100)),
                ('created_by_department_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_RISK_REVIEW', 'Under review by Risk Manager'), ('INFO_REQUESTED_BY_RISK_MANAGER', 'Information requested by Risk Manager'), ('REJECTED_BY_RISK_MANAGER', 'Rejected by Risk Manager'), ('COMMITTEE_REVIEW_1', 'Committee Review 1'), ('INFO_REQUESTED_BY_COMMITTEE', 'Information requested by committee'), ('ACCEPTED_FOR_MITIGATION', 'Approved for mitigation'), ('COMMITTEE_REVIEW_2', 'Committee Review 2'), ('ADDITIONAL_MITIGATION_REQUIRED', 'Additional mitigation is required.'), ('RISK_ACCEPTED', 'Risk accepted'), ('IN_MITIGATION', 'IN_MITIGATION'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed')], default='OPEN', max_length=2000)),
                ('probability', models.CharField(blank=True, choices=[('LOW', 'Low'), ('HIGH', 'High'), ('MEDIUM', 'Medium')], max_length=500, null=True)),
                ('Impact', models.CharField(blank=True, choices=[('SMALL', 'Small'), ('AVERAGE', 'Average'), ('HUGE', 'Huge'), ('CRITICAL', 'Critical')], max_length=500, null=True)),
                ('possible_loss', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('existing_controls_text', models.TextField(blank=True)),
                ('planned_controls_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='app.category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='app.department')),
                ('responsible_department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_director', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='app.risk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATE', 'create'), ('UPDATE', 'update'), ('DECISION', 'decision'), ('ASSIGNMENT', 'assignment'), ('FINANCIAL', 'financial'), ('COMMENT', 'comment'), ('REVIEW', 'review')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('by', models.CharField(max_length=500)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.risk')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='RiskActivityRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.riskactivity')),
            ],
        ),
        migrations.CreateModel(
            name='RiskDecition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decition_type', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request Info'), ('ACCEPT_RESIDUAL', 'Accept Residual Risk')], max_length=30)),
                ('decided_by', models.CharField(max_length=500)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='app.risk')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_decition', models.TextField(blank=True)),
                ('last_decition_at', models.DateTimeField(blank=True, null=True)),
                ('mitigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mitigation')),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='app.risk')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.riskdecition')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyRiskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('riskactivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.riskactivity')),
                ('riskdecision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.riskdecition')),
            ],
        ),
        migrations.AddIndex(
            model_name='riskactivity',
            index=models.Index(fields=['risk', 'type'], name='app_riskact_risk_id_71039e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskactivity',
            index=models.Index(fields=['at'], name='app_riskact_at_7a09c4_idx'),
        ),
    ]
