# Generated by Django 5.2.6 on 2026-03-25 11:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('risk_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('created_by_user_id', models.CharField(max_length=100)),
                ('created_by_department_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('impact_min', models.FloatField()),
                ('impact_most_likely', models.FloatField()),
                ('impact_max', models.FloatField()),
                ('expected_loss', models.FloatField(default=0)),
                ('severity', models.FloatField(default=0)),
                ('inherent_score', models.FloatField(blank=True, null=True)),
                ('residual_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('existing_controls_text', models.TextField(blank=True)),
                ('planned_controls_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='app.category')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='app.risk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_decision', models.TextField(blank=True)),
                ('last_decision_at', models.DateTimeField(blank=True, null=True)),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='app.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request Info'), ('ACCEPT_RESIDUAL', 'Accept Residual Risk')], max_length=30)),
                ('decided_by', models.CharField(max_length=500)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='app.risk')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREATE', 'create'), ('UPDATE', 'update'), ('DECISION', 'decision'), ('ASSIGNMENT', 'assignment'), ('FINANCIAL', 'financial'), ('COMMENT', 'comment'), ('REVIEW', 'review')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('by', models.CharField(max_length=500)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.risk')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['risk', 'type'], name='app_riskact_risk_id_71039e_idx'), models.Index(fields=['at'], name='app_riskact_at_7a09c4_idx')],
            },
        ),
    ]
